ДЗ 1
kvther1ne/2024-2-VK-EDU-Frontend-E-Tabunshchikova pull request #1
Opened 2024-09-23 08:31 UTC by kvther1ne

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ваш_назначенный_ментор проверить его.

Что было сделано:
* Реализованы функции convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js;
* Написан тест на функцию convertBytesToHumans.js.

2024-09-23 08:41 UTC, kgrechin requested changes
все хорошо, оставил несколько комментов, если есть вопросы, то пиши мне в телеграм

2024-09-23 08:41 UTC, kgrechin commented on convertBytesToHuman.js
> +  const value = bytes / Math.pow(1024, exponent);
интересное решение, а объясни пожалуйста, что происходит в этих двух строках, где используешь Math

2024-09-23 08:41 UTC, kgrechin commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman("string")).toBeFalsy();
добавь тесты на NaN, undefined, null, array, object, function

2024-09-23 08:41 UTC, kgrechin commented on correctSentence.js
> +  const startsWithUpperLetter = text.charAt(0).toUpperCase() + text.slice(1);
добавь проверку входного значения, что это строка и не пустая

2024-09-23 08:41 UTC, kgrechin commented on nonUniqueElements.js
> +    frequencyMap[integer] = (frequencyMap[integer] || 0) + 1;
хорошое решение, но я его уже оч много раз видел)

даю небольшое доп задание на рефакторинг:
нужно вместо объекта счетчика использовать Set.

2024-09-23 08:41 UTC, kgrechin commented on nonUniqueElements.js
> +
добавь проверку входного значения

2024-09-23 09:49 UTC, kvther1ne commented on convertBytesToHuman.js
> +  const value = bytes / Math.pow(1024, exponent);
Сначала определяем степень числа 1024 (= единицу измерения), потом - делим входные байты на 1024 в этой степени

2024-09-23 09:51 UTC, kvther1ne commented on convertBytesToHuman.js
> +  const value = bytes / Math.pow(1024, exponent);
Обновила пр

2024-09-23 10:05 UTC, kgrechin requested changes

2024-09-23 10:05 UTC, kgrechin commented on nonUniqueElements.js
> +
кажется тут можно ограничиться одним сетом, просто удаляя значение если оно уже в нем есть,  у сетя операции has, delete, add - o(1)

2024-09-23 10:05 UTC, kgrechin commented on nonUniqueElements.js
> +  if (!data.every((item) => typeof item === "number")) {
every - даст доп цикл, что не оч круто, лучше в одном цикле проверять значение и если не int, то выкидывать исключение

2024-09-23 10:05 UTC, kgrechin commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([5, 5, 5, 5, 5])).toEqual([5, 5, 5, 5, 5]);
тут теперь надо добавить тесты на выброс исключения

2024-09-26 05:31 UTC, kgrechin commented
@kvther1ne, ждем фиксов)

2024-10-02 05:53 UTC, kgrechin commented
@kvther1ne, напоминаю о фиксах

2024-10-07 19:54 UTC, martinkomitsky commented
@kvther1ne привет! будут ли исправления?

2024-10-08 05:13 UTC, kgrechin commented
kvther1ne: Привет!! Да, я заработалась и болела, совсем сил ни на что не было. Все сделаю)))

2024-10-27 18:00 UTC, martinkomitsky commented
@kvther1ne привет! как успехи? Получится вернуться к нам?

2024-10-27 18:31 UTC, kvther1ne commented
> @kvther1ne привет! как успехи? Получится вернуться к нам?

Привет! А еще не поздно?

2024-10-31 06:57 UTC, kgrechin commented
@kvther1ne, не поздно, но нужно сильно поторопиться, так как ребята уже на 7 дз

2024-10-31 10:51 UTC, martinkomitsky commented
> > @kvther1ne привет! как успехи? Получится вернуться к нам?
> 
> Привет! А еще не поздно?

да, есть хорошие шансы успеть! пожалуйста, поторопись и всё будет ок)

2024-11-07 07:21 UTC, kgrechin approved these changes
@kvther1ne, мержу 1 дз, функции все работают корректно, комменты я думаю понятны и если что разберешься с ними потом) можешь переходить ко 2 дз, если есть желание, все еще не поздно начать сдавать домашки))

2024-11-07 07:22 UTC, kgrechin commented
@kvther1ne, 12 баллов

2024-11-07 07:22 UTC, merged